/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.asset_management_app.assetsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DeviceInventory generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`DEVICE_INVENTORY`", uniqueConstraints = {
            @UniqueConstraint(name = "`UK_q9cfa2mynxhvqewf90xsyyg9h`", columnNames = {"`MODEL ID`"})})
public class DeviceInventory implements Serializable {

    private Integer deviceId;
    private Integer cost;
    private Date dateOfPurchase;
    private String displaySize;
    private String imageurl;
    private String memory;
    private String modelId;
    private String modelName;
    private String processor;
    private Integer qty;
    private String storage;
    private Date warrantExpiryDate;
    private String yearOfManufacture;
    private String catalogName;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`DEVICE ID`", nullable = false, scale = 0, precision = 10)
    public Integer getDeviceId() {
        return this.deviceId;
    }

    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    @Column(name = "`COST`", nullable = true, scale = 0, precision = 10)
    public Integer getCost() {
        return this.cost;
    }

    public void setCost(Integer cost) {
        this.cost = cost;
    }

    @Column(name = "`DATE OF PURCHASE`", nullable = true)
    public Date getDateOfPurchase() {
        return this.dateOfPurchase;
    }

    public void setDateOfPurchase(Date dateOfPurchase) {
        this.dateOfPurchase = dateOfPurchase;
    }

    @Column(name = "`DISPLAY SIZE`", nullable = true, length = 255)
    public String getDisplaySize() {
        return this.displaySize;
    }

    public void setDisplaySize(String displaySize) {
        this.displaySize = displaySize;
    }

    @Column(name = "`IMAGEURL`", nullable = true, length = 255)
    public String getImageurl() {
        return this.imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    @Column(name = "`MEMORY`", nullable = true, length = 255)
    public String getMemory() {
        return this.memory;
    }

    public void setMemory(String memory) {
        this.memory = memory;
    }

    @Column(name = "`MODEL ID`", nullable = true, length = 255)
    public String getModelId() {
        return this.modelId;
    }

    public void setModelId(String modelId) {
        this.modelId = modelId;
    }

    @Column(name = "`MODEL NAME`", nullable = true, length = 255)
    public String getModelName() {
        return this.modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    @Column(name = "`PROCESSOR`", nullable = true, length = 255)
    public String getProcessor() {
        return this.processor;
    }

    public void setProcessor(String processor) {
        this.processor = processor;
    }

    @Column(name = "`QTY`", nullable = true, scale = 0, precision = 10)
    public Integer getQty() {
        return this.qty;
    }

    public void setQty(Integer qty) {
        this.qty = qty;
    }

    @Column(name = "`STORAGE`", nullable = true, length = 255)
    public String getStorage() {
        return this.storage;
    }

    public void setStorage(String storage) {
        this.storage = storage;
    }

    @Column(name = "`WARRANT EXPIRY DATE`", nullable = true)
    public Date getWarrantExpiryDate() {
        return this.warrantExpiryDate;
    }

    public void setWarrantExpiryDate(Date warrantExpiryDate) {
        this.warrantExpiryDate = warrantExpiryDate;
    }

    @Column(name = "`YEAR OF MANUFACTURE`", nullable = true, length = 255)
    public String getYearOfManufacture() {
        return this.yearOfManufacture;
    }

    public void setYearOfManufacture(String yearOfManufacture) {
        this.yearOfManufacture = yearOfManufacture;
    }

    @Column(name = "`CATALOG_NAME`", nullable = true, length = 255)
    public String getCatalogName() {
        return this.catalogName;
    }

    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DeviceInventory)) return false;
        final DeviceInventory deviceInventory = (DeviceInventory) o;
        return Objects.equals(getDeviceId(), deviceInventory.getDeviceId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDeviceId());
    }
}